# config/lifecycle_mgr.yaml
#
# Example configuration file to automatically handle the ldlidar lifecycle node

/**:
  ros__parameters:
    autostart: true
    node_names: ['ldlidar_node']
    bond_timeout: 3.0